Add Hbase deployments and orchestrations workflows.
ow2-proactive/proactive-examples pull request #1122
Opened 2022-04-25 11:32 UTC by rsaidane

2022-04-25 13:11 UTC, mklkun commented
Retest this please

2022-04-25 13:54 UTC, fviale commented
Retest this please

2022-04-26 13:49 UTC, mklkun reviewed
Some comments should be tackled

2022-04-26 13:49 UTC, mklkun commented on Hbase/resources/catalog/Docker_Swarm_HDFS_Zookeeper_Hbase_Service.xml
> +                <variable name="SERVICE_ID" value="Docker_Swarm" inherited="false"  description="The name of the service. Please keep the default value for this variable."   />
`Please keep the default value for this variable.` Why not hiding the variable then (if it should not be changed) or advanced (if it can be changed by advanced users)?

2022-04-26 13:49 UTC, mklkun commented on Hbase/resources/catalog/Docker_Swarm_HDFS_Zookeeper_Hbase_Service.xml
> +                <variable name="TARGETED_PA_NODE_SOURCE_NAME" value="$node_source_name" inherited="false"     />
Please add a description to all variables.

2022-04-26 13:49 UTC, mklkun commented on Hbase/resources/catalog/Docker_Swarm_HDFS_Zookeeper_Hbase_Service.xml
> +                <variable name="SERVICE_ID" value="HDFS" inherited="false"  description="The name of the service. Please keep the default value for this variable."   />
Same

2022-04-26 13:49 UTC, mklkun commented on Hbase/resources/catalog/Hbase.xml
> +    sleep(10000000000)
Why sleep() after exit()?

2022-04-26 13:49 UTC, mklkun commented on HbaseOrchestration/resources/catalog/Hbase_Exec_Java_File.xml
> +        <variable name="Hbase_java_file" value="HelloHBase.java" model="PA:GLOBAL_FILE"   advanced="false" hidden="false"/>
Please add a description here

2022-04-26 13:49 UTC, mklkun commented on Hbase/resources/catalog/Docker_Swarm_HDFS_Zookeeper_Hbase_Service.xml
> +        <variable name="nb_hbase_hdfs_workers" value="1" model="PA:NOT_EMPTY_STRING"   advanced="false" hidden="false"/>
A variable description please

2022-04-26 13:49 UTC, mklkun commented on Hbase/resources/catalog/Hbase.xml
> +import org.ow2.proactive.pca.service.client.ApiClient
Using an inline code for all the workflow is a nightmare to maintain. Please make sure you have no choice before using your inline code instead of a generic pre, post or clean scripts from catalog.

2022-04-26 14:16 UTC, rsaidane commented on Hbase/resources/catalog/Docker_Swarm_HDFS_Zookeeper_Hbase_Service.xml
> +                <variable name="SERVICE_ID" value="Docker_Swarm" inherited="false"  description="The name of the service. Please keep the default value for this variable."   />
ok i ll change them to advanced

2022-04-26 16:28 UTC, rsaidane commented on Hbase/resources/catalog/Hbase.xml
> +import org.ow2.proactive.pca.service.client.ApiClient
Either I edit the zookeeper workflow to propagate the variables that I use for hbase workflow like the workflow HDFS or I call directly with inline code. If I edit the zookeeper workflow, I may break the other workflows that use zookeeper.

2022-04-26 16:29 UTC, rsaidane commented on HbaseOrchestration/resources/catalog/Hbase_Exec_Java_File.xml
> +        <variable name="main" value="HelloHBase"  description="main class"  advanced="false" hidden="false"/>
ok

2022-04-26 16:50 UTC, rsaidane commented on Hbase/resources/catalog/Docker_Swarm_HDFS_Zookeeper_Hbase_Service.xml
> +                <variable name="TARGETED_PA_NODE_SOURCE_NAME" value="$node_source_name" inherited="false"     />
ok

2022-04-26 16:50 UTC, rsaidane commented on Hbase/resources/catalog/Docker_Swarm_HDFS_Zookeeper_Hbase_Service.xml
> +                <variable name="SERVICE_ID" value="HDFS" inherited="false"  description="The name of the service. Please keep the default value for this variable."   />
ok

2022-04-28 08:12 UTC, mklkun approved these changes
LGTM

2022-04-28 14:50 UTC, mbenguig commented on Hbase/METADATA.json
> +				"name" : "HBASE",
HBase

2022-04-28 15:01 UTC, mbenguig commented on Hbase/resources/catalog/Docker_Swarm_HDFS_Zookeeper_Hbase_Service.xml
> +        <![CDATA[ Deploy a Docker Swarm-HDFS-Zookeeper-Hbase platform of nb_RegionServers and hdfs DataNodes. node_source_name refers to the targeted node source of the Hbase-HDFS deployment. ]]>
nb_RegionServers and hdfs DataNodes -> where are these params ?

2022-04-28 15:02 UTC, mbenguig commented on Hbase/resources/catalog/Docker_Swarm_HDFS_Zookeeper_Hbase_Service.xml
> +        <![CDATA[ Deploy a Docker Swarm-HDFS-Zookeeper-Hbase platform of nb_RegionServers and hdfs DataNodes. node_source_name refers to the targeted node source of the Hbase-HDFS deployment. ]]>
"Hbase-HDFS deployment" -> "platform deployment"

2022-04-28 15:06 UTC, rsaidane commented on Hbase/resources/catalog/Docker_Swarm_HDFS_Zookeeper_Hbase_Service.xml
> +        <![CDATA[ Deploy a Docker Swarm-HDFS-Zookeeper-Hbase platform of nb_RegionServers and hdfs DataNodes. node_source_name refers to the targeted node source of the Hbase-HDFS deployment. ]]>
nb_hbase_hdfs_workers a single parameter for both

2022-04-28 15:07 UTC, mbenguig commented on Hbase/resources/catalog/Docker_Swarm_HDFS_Zookeeper_Hbase_Service.xml
> +                <variable name="TARGETED_PA_NODE_SOURCE_NAME" value="$node_source_name" inherited="false"  description="TARGETED_PA_NODE_SOURCE_NAME refers to the targeted node source of the Hbase-HD
"Hbase-HDFS deployment" -> "Docker Swarm"

2022-04-28 15:11 UTC, mbenguig commented on Hbase/resources/catalog/Docker_Swarm_HDFS_Zookeeper_Hbase_Service.xml
> +                <variable name="swarm_service_instance_id" value="$propagated_swarm_service_instance_id" inherited="false"  description="Instance id of swarm service"  advanced="false" hidden="false"
"Instance id of swarm service" -> "Instance id of the targeted Docker Swarm service"

2022-04-28 15:12 UTC, rsaidane commented on Hbase/METADATA.json
> +				"name" : "HBASE",
ok

2022-04-28 15:14 UTC, rsaidane commented on Hbase/resources/catalog/Docker_Swarm_HDFS_Zookeeper_Hbase_Service.xml
> +                <variable name="swarm_service_instance_id" value="$propagated_swarm_service_instance_id" inherited="false"  description="Instance id of swarm service"  advanced="false" hidden="false"
ok

2022-04-28 15:14 UTC, mbenguig commented on Hbase/resources/catalog/Docker_Swarm_HDFS_Zookeeper_Hbase_Service.xml
> +                <variable name="hdfs_service_instance_id" value="$propagated_hdfs_service_instance_id" inherited="false"  description="The instance ID of HDFS  service"  advanced="false" hidden="fals
"The instance ID of HDFS service" -> "The instance ID of the targeted HDFS service"

2022-04-28 15:16 UTC, mbenguig commented on Hbase/resources/catalog/Docker_Swarm_HDFS_Zookeeper_Hbase_Service.xml
> +                <variable name="ZOOKEEPER_INSTANCE_ID" value="$propagated_Zookeeper_service_instance_id" inherited="false"  description="The instance ID of Zookeeper service"  advanced="false" hidden
"The instance ID of Zookeeper service" -> "The instance ID of the Zookeeper service"

2022-04-28 15:19 UTC, mbenguig commented on Hbase/resources/catalog/Docker_Swarm_HDFS_Zookeeper_Hbase_Service.xml
> +                <variable name="INSTANCE_NAME" value="hbase-$PA_JOB_ID" inherited="false"  description="The name of the service to be deployed"  advanced="false" hidden="false"/>
description="The name of the service to be deployed" ??

2022-04-28 15:20 UTC, mbenguig commented on Hbase/resources/catalog/Docker_Swarm_HDFS_Zookeeper_Hbase_Service.xml
> +                <variable name="INSTANCE_NAME" value="hdfs-$PA_JOB_ID" inherited="false"  description="The name of the service to be deployed"   />
"The name of the service to be deployed" -> "The name of the service to be undeployed"

2022-04-28 15:21 UTC, mbenguig commented on Hbase/resources/catalog/Docker_Swarm_HDFS_Zookeeper_Hbase_Service.xml
> +                <variable name="INSTANCE_NAME" value="swarm-$PA_JOB_ID" inherited="false"  description="The name of the service to be deployed"   />
"The name of the service to be deployed" -> "The name of the service to be undeployed"

2022-04-28 15:22 UTC, mbenguig commented on Hbase/resources/catalog/Docker_Swarm_HDFS_Zookeeper_Hbase_Service.xml
> +                <variable name="INSTANCE_NAME" value="zookeeper-server-${PA_JOB_ID}" inherited="false"    advanced="false" hidden="false"/>
"INSTANCE_NAME"-> missing description

2022-04-28 15:31 UTC, rsaidane commented on Hbase/resources/catalog/Docker_Swarm_HDFS_Zookeeper_Hbase_Service.xml
> +                <variable name="TARGETED_PA_NODE_SOURCE_NAME" value="$node_source_name" inherited="false"  description="TARGETED_PA_NODE_SOURCE_NAME refers to the targeted node source of the Hbase-HD
ok

2022-04-28 15:33 UTC, rsaidane commented on Hbase/resources/catalog/Docker_Swarm_HDFS_Zookeeper_Hbase_Service.xml
> +                <variable name="hdfs_service_instance_id" value="$propagated_hdfs_service_instance_id" inherited="false"  description="The instance ID of HDFS  service"  advanced="false" hidden="fals
ok

2022-04-28 15:33 UTC, rsaidane commented on Hbase/resources/catalog/Docker_Swarm_HDFS_Zookeeper_Hbase_Service.xml
> +                <variable name="ZOOKEEPER_INSTANCE_ID" value="$propagated_Zookeeper_service_instance_id" inherited="false"  description="The instance ID of Zookeeper service"  advanced="false" hidden
ok

2022-04-28 15:38 UTC, rsaidane commented on Hbase/resources/catalog/Docker_Swarm_HDFS_Zookeeper_Hbase_Service.xml
> +                <variable name="INSTANCE_NAME" value="hdfs-$PA_JOB_ID" inherited="false"  description="The name of the service to be deployed"   />
ok

2022-04-28 15:38 UTC, rsaidane commented on Hbase/resources/catalog/Docker_Swarm_HDFS_Zookeeper_Hbase_Service.xml
> +                <variable name="INSTANCE_NAME" value="swarm-$PA_JOB_ID" inherited="false"  description="The name of the service to be deployed"   />
ok

2022-04-28 15:39 UTC, rsaidane commented on Hbase/resources/catalog/Docker_Swarm_HDFS_Zookeeper_Hbase_Service.xml
> +                <variable name="INSTANCE_NAME" value="zookeeper-server-${PA_JOB_ID}" inherited="false"    advanced="false" hidden="false"/>
ok I ll add description="The name of the service to be undeployed"

2022-04-29 07:03 UTC, mbenguig commented on Hbase/resources/catalog/Finish_Hbase.xml
> +  variables.put("DOCKER_RM_FORCED_EXECUTED")
variables.put("DOCKER_RM_FORCED_EXECUTED") ? Is there no second argument ? What do you put ?

2022-04-29 07:09 UTC, mbenguig commented on Hbase/resources/catalog/Finish_Hbase.xml
> +status_file_content += variables.get("DOCKER_RM_FORCED_EXECUTED")
variables.get("DOCKER_RM_FORCED_EXECUTED") -> how do you retrieve the DIFFERENT clean status of EACH replicated task ?

2022-04-29 07:20 UTC, mbenguig commented on Hbase/resources/catalog/Hbase.xml
> +        <variable name="ZOOKEEPER_INSTANCE_ID" value="xx" model="PA:NOT_EMPTY_STRING"   advanced="false" hidden="false"/>
ZOOKEEPER_INSTANCE_ID -> zookeeper_instance_id

2022-04-29 07:27 UTC, mbenguig commented on Hbase/resources/catalog/Hbase.xml
> +import org.ow2.proactive.pca.service.client.ApiClient
I agree with @mklkun .. the following inline script is only supposed to gather useful variables from the zookeeper service instance.... Consequently, you are supposed to rely on the Retrieve_variables_from_service_instance_id script as you did for HDFS.

2022-04-29 07:35 UTC, mbenguig commented on Hbase/resources/catalog/Hbase.xml
> +def hbase_pa_node_name = variables.get("hbase_pa_node_name")
Could you add a comment to precise which process you are monitoring (running on hbase_pa_node_name)?

2022-04-29 07:36 UTC, mbenguig commented on Hbase/resources/catalog/Hbase.xml
> +def hbase_pa_node_name = variables.get("hbase_pa_node_name")
Could you add a comment to explain why looping on hbase_pa_node_name ?

2022-04-29 07:43 UTC, mbenguig commented on Hbase/resources/catalog/Hbase.xml
> +selected = System.getProperty("proactive.node.nodesource").equals(variables.get("TARGETED_PA_NODE_SOURCE_NAME"))
Do you control the master, backup master, thrift server run on diffferent nodes ?

2022-04-29 07:47 UTC, rsaidane commented on Hbase/resources/catalog/Hbase.xml
> +selected = System.getProperty("proactive.node.nodesource").equals(variables.get("TARGETED_PA_NODE_SOURCE_NAME"))
yes same as a regionServer (worker)

2022-04-29 07:49 UTC, mbenguig commented on Hbase/resources/catalog/Hbase.xml
> +def nb_deployments_total = (variables.get("nb_hbase_region_servers") as Integer) + 4
Small comment to explain "+4"

2022-04-29 07:52 UTC, mbenguig commented on HbaseOrchestration/resources/catalog/Hbase_Exec_Java_File.xml
> +        <variable name="Hbase_java_file" value="HelloHBase.java" model="PA:GLOBAL_FILE" description="Upload a java file to execute HBase commands or run the &quot;HelloHBase.java&quot; " group="" adv
Like your first variable "Hbase_java_file" -> "hbase_java_file"

2022-04-29 07:54 UTC, mbenguig commented on HbaseOrchestration/resources/catalog/Hbase_Exec_Java_File.xml
> +        <variable name="Hbase_java_file" value="HelloHBase.java" model="PA:GLOBAL_FILE" description="Upload a java file to execute HBase commands or run the &quot;HelloHBase.java&quot; " group="" adv
"or run the HelloHBase.java" -> "or run HelloHBase.java"
+ is it the default behavior if the hbase_java_file is left empty ?

2022-04-29 07:56 UTC, rsaidane commented on HbaseOrchestration/resources/catalog/Hbase_Exec_Java_File.xml
> +        <variable name="Hbase_java_file" value="HelloHBase.java" model="PA:GLOBAL_FILE" description="Upload a java file to execute HBase commands or run the &quot;HelloHBase.java&quot; " group="" adv
if the file HelloHBase.java is in globalspace yes

2022-04-29 07:57 UTC, rsaidane commented on Hbase/resources/catalog/Hbase.xml
> +def nb_deployments = (variables.get("nb_hbase_region_servers") as Integer) + 3
ok

2022-04-29 07:57 UTC, rsaidane commented on Hbase/resources/catalog/Hbase.xml
> +def nb_deployments_total = (variables.get("nb_hbase_region_servers") as Integer) + 4
ok

2022-04-29 08:24 UTC, mbenguig commented on HbaseOrchestration/resources/catalog/Hbase_Exec_Java_File.xml
> +command_in_container = hbase_Java_file_config_command
"command_in_container = hbase_Java_file_config_command" -> Use directly hbase_Java_file_config_command

2022-04-29 08:25 UTC, mbenguig commented on HbaseOrchestration/resources/catalog/Hbase_Exec_Java_File.xml
> +cmd = ["docker", "exec", hbase_example_container_name, "/bin/sh", "-c", command_in_container]
"command_in_container" -> "hbase_Java_file_config_command"

2022-04-29 08:28 UTC, mbenguig commented on HbaseOrchestration/resources/catalog/Hbase_Exec_Java_File.xml
> +if(!java_compile_ok) {
Why if the compilation failed you still execute the java main file?

2022-04-29 08:29 UTC, mbenguig commented on HbaseOrchestration/resources/catalog/Hbase_Exec_Java_File.xml
> +    for(int i = 0; i<10; i++){
A small comment to explain this for loop

2022-04-29 08:33 UTC, mbenguig commented on HbaseOrchestration/resources/catalog/Hbase_Exec_Java_File.xml
> +        <variable name="Hbase_java_file" value="HelloHBase.java" model="PA:GLOBAL_FILE" description="Upload a java file to execute HBase commands or run the &quot;HelloHBase.java&quot; " group="" adv
"Upload a java file to execute HBase commands or run the &quot;HelloHBase.java&quot; " 
->
"Upload a java file to execute HBase commands"

2022-04-29 08:33 UTC, mbenguig requested changes
See comments

2022-04-29 14:54 UTC, mbenguig commented on Hbase/resources/catalog/Docker_Swarm_HDFS_Zookeeper_Hbase_Service.xml
> +        <![CDATA[ Deploy a Docker Swarm-HDFS-Zookeeper-Hbase platform of nb_RegionServers and hdfs DataNodes. node_source_name refers to the targeted node source of the Hbase-HDFS deployment. ]]>
Ok so rephrase the description: -> "Deploy a Docker Swarm-HDFS-Zookeeper-Hbase platform of nb_hbase_hdfs_workers region servers and hdfs data nodes."

2022-04-29 14:56 UTC, mbenguig commented on Hbase/resources/catalog/Hbase.xml
> +        <variable name="ZOOKEEPER_INSTANCE_ID" value="xx" model="PA:NOT_EMPTY_STRING"   advanced="false" hidden="false"/>
?

2022-04-29 15:06 UTC, mbenguig commented on HbaseOrchestration/resources/catalog/Hbase_Exec_Java_File.xml
> +    for(int i = 0; i<10; i++){
?

2022-04-29 15:07 UTC, mbenguig commented on HbaseOrchestration/resources/catalog/Hbase_Exec_Java_File.xml
> +        <variable name="Hbase_java_file" value="HelloHBase.java" model="PA:GLOBAL_FILE" description="Upload a java file to execute HBase commands or run the &quot;HelloHBase.java&quot; " group="" adv
?

2022-04-29 15:09 UTC, mbenguig commented on Hbase/resources/catalog/Finish_Hbase.xml
> +status_file_content += variables.get("DOCKER_RM_FORCED_EXECUTED")
?

2022-04-29 15:11 UTC, mbenguig commented on Hbase/METADATA.json
> +				"name" : "HBASE",
Not done ...check all hbase occurences .. either these should be keep in lower cases (technical constraint.. or you need to respect the original name "HBase"

2022-04-29 15:13 UTC, mbenguig commented on Hbase/resources/catalog/Docker_Swarm_HDFS_Zookeeper_Hbase_Service.xml
> +        <![CDATA[ Deploy a Docker Swarm-HDFS-Zookeeper-Hbase platform of nb_RegionServers and hdfs DataNodes. node_source_name refers to the targeted node source of the Hbase-HDFS deployment. ]]>
?

2022-05-05 09:27 UTC, mbenguig approved these changes
Nice ! thxx

2022-05-05 10:29 UTC, merged