Add Run_SSIS_Package data connector wf, Knime pca service and fix FTP wf
ow2-proactive/proactive-examples pull request #749
Opened 2020-09-21 17:05 UTC by aminelouati

In this PR, we:
1. Add  Run_SSIS_Package wf in data connectors bucket
2. Add Knime pca service
3. Fix FTP wf

2020-09-21 17:08 UTC, fviale commented on DataConnectors/resources/catalog/Run_SSIS_Package.xml
> +cd C:\Program Files\Microsoft SQL Server\150\DTS\Binn
This path should be configurable. SSIs is not necessarily installed in C:

2020-09-21 17:09 UTC, fviale commented on DataConnectors/resources/catalog/Run_SSIS_Package.xml
> +echo Running SSIS Packages in 32-Bit
why is there no cd instruction here. Do you assume, DTExec is in the Path ? I doubt it is present by default

2020-09-21 17:15 UTC, andrewssobral requested changes

2020-09-21 17:15 UTC, andrewssobral commented on Knime/METADATA.json
> +        "name": "Knime_OpenRefine",
`"name": "Finish_Knime",`

2020-09-21 17:15 UTC, andrewssobral commented on Knime/resources/catalog/Knime.xml
> +    <variable name="INSTANCE_NAME" value="knime-instance" model=""/>
`<variable name="INSTANCE_NAME" value="knime-instance-$PA_JOB_ID" model=""/>`

2020-09-21 17:15 UTC, andrewssobral commented on Knime/resources/catalog/Knime.xml
> +    <variable name="ENDPOINT_ID" value="knime-gui" />
`<variable name="ENDPOINT_ID" value="knime-gui-$PA_JOB_ID" />`

2020-09-21 17:15 UTC, andrewssobral commented on Knime/resources/catalog/Knime.xml
> +KNIME_HOST_PORT=$variables_SERVICE_PORT
Workflow variable `SERVICE_PORT` does not exists.
It's default value should be `-1`.

2020-09-22 08:54 UTC, fviale commented on DataConnectors/resources/catalog/Run_SSIS_Package.xml
> +SSIS_PACKAGE_PATH (required) is the full path of the SSIS package deployed on the Integration Services server.
could you provide a path example in the description for both paths ?

2020-09-22 09:13 UTC, fviale commented on DataConnectors/resources/catalog/Run_SSIS_Package.xml
> +SSIS_PACKAGE_PATH (required) is the full path of the SSIS package deployed on the Integration Services server. For example, \SSISDB\Test Package\testSSIS\Package.dtsx.
is it not C:\... ?

2020-09-22 09:15 UTC, andrewssobral approved these changes

2020-09-22 09:19 UTC, aminelouati commented on DataConnectors/resources/catalog/Run_SSIS_Package.xml
> +SSIS_PACKAGE_PATH (required) is the full path of the SSIS package deployed on the Integration Services server. For example, \SSISDB\Test Package\testSSIS\Package.dtsx.
Non the package is located inside the Integration Service server

2020-09-22 09:34 UTC, fviale commented on DataConnectors/resources/catalog/Run_SSIS_Package.xml
> +SSIS_PACKAGE_PATH (required) is the full path of the SSIS package deployed on the Integration Services server. For example, \SSISDB\Test Package\testSSIS\Package.dtsx.
ok

2020-09-22 09:34 UTC, fviale approved these changes

2020-09-22 09:38 UTC, merged