Add a first version of Deep Learning as a Service (DLaaS) PCA service
ow2-proactive/proactive-examples pull request #779
Opened 2020-12-17 11:23 UTC by ImenBizid

In this PR, we add a new PCA service DLaaS, this service manage the deployment of tensorflow models.
It is based on TensorFlow Serving TFX. We have created different endpoints enabling the management of the life cycle of Tensorflow models deployment/undeployment.
The scripts (utils.py, dlaas.proto, dlaas_pb2.py) handling the creation and editing of the config file were added in the docker image activeeon/dlaas. you can find these scripts and the related dockerfile in the github repository docker.

2020-12-17 12:05 UTC, andrewssobral requested changes
Thank you @ImenBizid for this nice work.
Please, uniform the file and directory names to DLaaS.
Some files are DLaaS and others are Dlaas.

2020-12-23 08:46 UTC, dianajlailaty approved these changes

2020-12-23 08:47 UTC, dianajlailaty approved these changes

2020-12-23 11:50 UTC, andrewssobral approved these changes

2020-12-23 13:42 UTC, merged