Add Signal Task Templates
ow2-proactive/proactive-examples pull request #794
Opened 2021-01-21 19:53 UTC by nebilbenmabrouk

2021-01-22 16:35 UTC, fviale commented on Signals/resources/catalog/Send_Signal.xml
> +signalapi.addSignal(variables.get("SIGNAL"))
just saw this, sorry I didn't mention it earlier. I would have prefered sendSignal rather then addSignal

2021-01-22 16:38 UTC, fviale commented
@nebilbenmabrouk why only workflows ? We could also have some pre and post scripts (referenced enventually by these workflows). 
Something like 

wait_for_signal.groovy (1 argument):
signal = args[0]
println("Waiting for signal "+ signal)
signalapi.waitFor(signal)

ready_for_signal.groovy (1 argument):
signal = args[0]
println("Ready for signal "+ signal)
signalapi.readyForSignal(signal)

2021-01-22 16:41 UTC, nebilbenmabrouk commented on Signals/resources/catalog/Send_Signal.xml
> +signalapi.addSignal(variables.get("SIGNAL"))
OK, I'll do 2 new PRs one for scheduling and one for proactive-examples. Thanks

2021-01-24 20:15 UTC, amouhoub commented
@nebilbenmabrouk You must add the following line to `build.gradle` in order for your bucket to be included
```include 'Signals/**'```
You must also add the bucket name to the `ordered_bucket_list` file as well

2021-01-24 20:33 UTC, amouhoub requested changes

2021-01-24 20:33 UTC, amouhoub commented on Signals/METADATA.json
> +		"bucket" : "Signal",
@nebilbenmabrouk bucket name should be all lowercase, even here

2021-01-24 21:06 UTC, nebilbenmabrouk commented on Signals/METADATA.json
> +		"bucket" : "Signal",
Done :)

2021-01-24 21:59 UTC, merged