Improve management workflows by adding description and changing stop signal's name
ow2-proactive/proactive-examples pull request #891
Opened 2021-04-20 14:49 UTC by mklkun

2021-04-20 15:45 UTC, dianajlailaty requested changes

2021-04-20 15:45 UTC, dianajlailaty commented on MaaSDLPCA/resources/catalog/MaaS_DL_Service.xml
> +    <![CDATA[ This service allows to launch an instance of MaaS_DL under the name: INSTANCE_NAME, through ProActive Cloud Automation (PCA) Portal. Using the launched instance, an already built, teste
ProActive Service Automation instead of ProActive Cloud Automation

2021-04-20 15:45 UTC, dianajlailaty commented on MaaSMLPCA/resources/catalog/MaaS_ML_Service.xml
> +    <![CDATA[ This service allows to launch an instance of MaaS_ML under the name: INSTANCE_NAME, through ProActive Cloud Automation (PCA) Portal. Using the launched instance, an already built, teste
same comment PSA instead of PCA

2021-04-20 16:53 UTC, mklkun commented on MaaSDLPCA/resources/catalog/MaaS_DL_Service.xml
> +    <![CDATA[ This service allows to launch an instance of MaaS_DL under the name: INSTANCE_NAME, through ProActive Cloud Automation (PCA) Portal. Using the launched instance, an already built, teste
Hmmm these should be corrected in the main workflows of PSA then. I copied the description from there.
I will do it. Thanks!

2021-04-20 16:53 UTC, mklkun commented on MaaSMLPCA/resources/catalog/MaaS_ML_Service.xml
> +    <![CDATA[ This service allows to launch an instance of MaaS_ML under the name: INSTANCE_NAME, through ProActive Cloud Automation (PCA) Portal. Using the launched instance, an already built, teste
Same

2021-04-21 07:59 UTC, Hiba-Alili approved these changes

2021-04-21 08:38 UTC, dianajlailaty approved these changes

2021-04-21 09:01 UTC, merged